CXX = g++
CXXFLAGS = -std=c++11
LIBS = -lcurl -ljsoncpp

all: xahseelqjgcx

xahseelqjgcx: xahseelqjgcx.o
	$(CXX) $(CXXFLAGS) -o xahseelqjgcx xahseelqjgcx.o $(LIBS)

xahseelqjgcx.o: xahseelqjgcx.cpp
	$(CXX) $(CXXFLAGS) -c xahseelqjgcx.cpp

clean:
	rm -f xahseelqjgcx xahseelqjgcx.o
